name: Semgrep SAST

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  semgrep:
    name: Semgrep SAST Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Run Semgrep
        uses: semgrep/semgrep-action@v1
        with:
          config: p/php

      - name: Generate Semgrep JSON Report
        if: always()
        run: |
          semgrep scan --config p/php --json --output semgrep-automation-report.json .

      - name: Upload Semgrep JSON Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-automation-report
          path: semgrep-automation-report.json
          if-no-files-found: error